<a href="https://colab.research.google.com/github/Mukeshburdak/Development-of-AI-Based-Knowledge-Retrieval-Platform-with-Query-Resolution-System/blob/main/Sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Prompt: Create a simple student table in MySQL with student records and demonstrate basic INSERT, SELECT, WHERE, AND/OR, UPDATE, and DELETE operations.

In [ ]:

# -- Topic 1: CREATE TABLE --
create_table_sql = """
CREATE TABLE IF NOT EXISTS Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Age INT,
    Major VARCHAR(100),
    GPA DECIMAL(3, 2)
);
"""

# -- Topic 2: INSERT INTO --
insert_sql = """
INSERT INTO Students (StudentID, FirstName, LastName, Age, Major, GPA) VALUES
(1, 'Alice', 'Smith', 20, 'Computer Science', 3.8),
(2, 'Bob', 'Johnson', 21, 'Mathematics', 3.4),
(3, 'Charlie', 'Brown', 19, 'Physics', 2.9),
(4, 'Diana', 'Davis', 22, 'Computer Science', 3.95),
(5, 'Evan', 'Miller', 20, 'Chemistry', 3.1);
"""

# -- Topic 3: SELECT --
select_all_sql = """
SELECT * FROM Students;
"""

# -- Topic 4: WHERE --
where_sql = """
SELECT * FROM Students
WHERE GPA > 3.5;
"""

# -- Topic 5: AND, OR --
and_or_sql = """
SELECT * FROM Students
WHERE Major = 'Computer Science' AND GPA >= 3.8;
"""

# -- Topic 6: UPDATE --
update_sql = """
UPDATE Students
SET GPA = 3.5
WHERE StudentID = 2;
"""

# -- Topic 7: DELETE --
delete_sql = """
DELETE FROM Students
WHERE StudentID = 5;
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

cursor.execute(create_table_sql)
cursor.execute(insert_sql)
print("--- Students Table ---")
print(pd.read_sql_query(select_all_sql, conn).to_string(index=False))
conn.close()

--- Students Table ---
 StudentID FirstName LastName  Age            Major  GPA
         1     Alice    Smith   20 Computer Science 3.80
         2       Bob  Johnson   21      Mathematics 3.40
         3   Charlie    Brown   19          Physics 2.90
         4     Diana    Davis   22 Computer Science 3.95
         5      Evan   Miller   20        Chemistry 3.10

## Prompt: Sort the students table by GPA in descending order using SQL.

In [ ]:
# -- Topic 8: ORDER BY --
order_by_sql = """
SELECT * FROM Students
ORDER BY GPA DESC;
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Age INT,
    Major VARCHAR(100),
    GPA DECIMAL(3, 2)
);
""")
cursor.execute("""
INSERT INTO Students (StudentID, FirstName, LastName, Age, Major, GPA) VALUES
(1, 'Alice', 'Smith', 20, 'Computer Science', 3.8),
(2, 'Bob', 'Johnson', 21, 'Mathematics', 3.4),
(3, 'Charlie', 'Brown', 19, 'Physics', 2.9),
(4, 'Diana', 'Davis', 22, 'Computer Science', 3.95),
(5, 'Evan', 'Miller', 20, 'Chemistry', 3.1);
""")

df_order = pd.read_sql_query(order_by_sql, conn)
display(df_order)
conn.close()

   StudentID FirstName LastName  Age             Major   GPA
0          4     Diana    Davis   22  Computer Science  3.95
1          1     Alice    Smith   20  Computer Science  3.80
2          2       Bob  Johnson   21       Mathematics  3.40
3          5      Evan   Miller   20         Chemistry  3.10
4          3   Charlie    Brown   19           Physics  2.90

## Prompt: Find the minimum and maximum GPA from the students table using SQL.

In [ ]:
# -- Topic 9: MIN() and MAX() --
min_max_sql = """
SELECT MIN(GPA) AS LowestGPA, MAX(GPA) AS HighestGPA FROM Students;
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Age INT,
    Major VARCHAR(100),
    GPA DECIMAL(3, 2)
);
""")
cursor.execute("""
INSERT INTO Students (StudentID, FirstName, LastName, Age, Major, GPA) VALUES
(1, 'Alice', 'Smith', 20, 'Computer Science', 3.8),
(2, 'Bob', 'Johnson', 21, 'Mathematics', 3.4),
(3, 'Charlie', 'Brown', 19, 'Physics', 2.9),
(4, 'Diana', 'Davis', 22, 'Computer Science', 3.95),
(5, 'Evan', 'Miller', 20, 'Chemistry', 3.1);
""")

df_min_max = pd.read_sql_query(min_max_sql, conn)
display(df_min_max)
conn.close()

   LowestGPA  HighestGPA
0        2.9        3.95

## Prompt: Count the total number of students, calculate their average age, and sum their GPAs using SQL.

In [ ]:
# -- Topic 10: COUNT(), AVG(), SUM() --
stats_sql = """
SELECT
    COUNT(StudentID) AS TotalStudents,
    AVG(Age) AS AverageAge,
    SUM(GPA) AS CumulativeGPA
FROM Students;
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Age INT,
    Major VARCHAR(100),
    GPA DECIMAL(3, 2)
);
""")
cursor.execute("""
INSERT INTO Students (StudentID, FirstName, LastName, Age, Major, GPA) VALUES
(1, 'Alice', 'Smith', 20, 'Computer Science', 3.8),
(2, 'Bob', 'Johnson', 21, 'Mathematics', 3.4),
(3, 'Charlie', 'Brown', 19, 'Physics', 2.9),
(4, 'Diana', 'Davis', 22, 'Computer Science', 3.95),
(5, 'Evan', 'Miller', 20, 'Chemistry', 3.1);
""")

df_stats = pd.read_sql_query(stats_sql, conn)
display(df_stats)
conn.close()

   TotalStudents  AverageAge  CumulativeGPA
0              5        20.4          17.15

## Prompt: Find all students whose first name starts with 'A' using the LIKE operator in SQL.

In [ ]:
# -- Topic 11: LIKE Operator --
like_sql = """
SELECT * FROM Students
WHERE FirstName LIKE 'A%';
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Age INT,
    Major VARCHAR(100),
    GPA DECIMAL(3, 2)
);
""")
cursor.execute("""
INSERT INTO Students (StudentID, FirstName, LastName, Age, Major, GPA) VALUES
(1, 'Alice', 'Smith', 20, 'Computer Science', 3.8),
(2, 'Bob', 'Johnson', 21, 'Mathematics', 3.4),
(3, 'Charlie', 'Brown', 19, 'Physics', 2.9),
(4, 'Diana', 'Davis', 22, 'Computer Science', 3.95),
(5, 'Evan', 'Miller', 20, 'Chemistry', 3.1);
""")

df_like = pd.read_sql_query(like_sql, conn)
display(df_like)
conn.close()

   StudentID FirstName LastName  Age             Major  GPA
0          1     Alice    Smith   20  Computer Science  3.8

## Prompt: Find all students who are majoring in either 'Computer Science' or 'Chemistry' using the IN operator in SQL.

In [ ]:
# -- Topic 12: IN Operator --
in_sql = """
SELECT * FROM Students
WHERE Major IN ('Computer Science', 'Chemistry');
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Age INT,
    Major VARCHAR(100),
    GPA DECIMAL(3, 2)
);
""")
cursor.execute("""
INSERT INTO Students (StudentID, FirstName, LastName, Age, Major, GPA) VALUES
(1, 'Alice', 'Smith', 20, 'Computer Science', 3.8),
(2, 'Bob', 'Johnson', 21, 'Mathematics', 3.4),
(3, 'Charlie', 'Brown', 19, 'Physics', 2.9),
(4, 'Diana', 'Davis', 22, 'Computer Science', 3.95),
(5, 'Evan', 'Miller', 20, 'Chemistry', 3.1);
""")

df_in = pd.read_sql_query(in_sql, conn)
display(df_in)
conn.close()

   StudentID FirstName LastName  Age             Major   GPA
0          1     Alice    Smith   20  Computer Science  3.80
1          4     Diana    Davis   22  Computer Science  3.95
2          5      Evan   Miller   20         Chemistry  3.10

## Prompt: Find all students whose age is between 20 and 22 inclusive using the BETWEEN operator in SQL.

In [ ]:
# -- Topic 13: BETWEEN Operator --
between_sql = """
SELECT * FROM Students
WHERE Age BETWEEN 20 AND 22;
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Age INT,
    Major VARCHAR(100),
    GPA DECIMAL(3, 2)
);
""")
cursor.execute("""
INSERT INTO Students (StudentID, FirstName, LastName, Age, Major, GPA) VALUES
(1, 'Alice', 'Smith', 20, 'Computer Science', 3.8),
(2, 'Bob', 'Johnson', 21, 'Mathematics', 3.4),
(3, 'Charlie', 'Brown', 19, 'Physics', 2.9),
(4, 'Diana', 'Davis', 22, 'Computer Science', 3.95),
(5, 'Evan', 'Miller', 20, 'Chemistry', 3.1);
""")

df_between = pd.read_sql_query(between_sql, conn)
display(df_between)
conn.close()

   StudentID FirstName LastName  Age             Major   GPA
0          1     Alice    Smith   20  Computer Science  3.80
1          2       Bob  Johnson   21       Mathematics  3.40
2          4     Diana    Davis   22  Computer Science  3.95
3          5      Evan   Miller   20         Chemistry  3.10

## Prompt: Select the student's first name with the alias 'Name' and major with the alias 'Course' using SQL Aliases.

In [ ]:
# -- Topic 14: Aliases --
aliases_sql = """
SELECT FirstName AS Name, Major AS Course FROM Students;
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Age INT,
    Major VARCHAR(100),
    GPA DECIMAL(3, 2)
);
""")
cursor.execute("""
INSERT INTO Students (StudentID, FirstName, LastName, Age, Major, GPA) VALUES
(1, 'Alice', 'Smith', 20, 'Computer Science', 3.8),
(2, 'Bob', 'Johnson', 21, 'Mathematics', 3.4),
(3, 'Charlie', 'Brown', 19, 'Physics', 2.9),
(4, 'Diana', 'Davis', 22, 'Computer Science', 3.95),
(5, 'Evan', 'Miller', 20, 'Chemistry', 3.1);
""")

df_aliases = pd.read_sql_query(aliases_sql, conn)
display(df_aliases)
conn.close()

      Name            Course
0    Alice  Computer Science
1      Bob       Mathematics
2  Charlie           Physics
3    Diana  Computer Science
4     Evan         Chemistry

## Prompt: Join the Students table with a Grades table to select student names and their corresponding letter grade using an INNER JOIN.

In [ ]:
# -- Topic 15: Joins (INNER JOIN) --
join_sql = """
SELECT Students.FirstName, Students.LastName, Grades.LetterGrade
FROM Students
INNER JOIN Grades ON Students.StudentID = Grades.StudentID;
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Age INT,
    Major VARCHAR(100),
    GPA DECIMAL(3, 2)
);
""")
cursor.execute("""
CREATE TABLE Grades (
    GradeID INT PRIMARY KEY,
    StudentID INT,
    LetterGrade VARCHAR(2)
);
""")
cursor.execute("""
INSERT INTO Students (StudentID, FirstName, LastName, Age, Major, GPA) VALUES
(1, 'Alice', 'Smith', 20, 'Computer Science', 3.8),
(2, 'Bob', 'Johnson', 21, 'Mathematics', 3.4),
(3, 'Charlie', 'Brown', 19, 'Physics', 2.9);
""")
cursor.execute("""
INSERT INTO Grades (GradeID, StudentID, LetterGrade) VALUES
(101, 1, 'A'),
(102, 2, 'B'),
(103, 3, 'C');
""")

df_join = pd.read_sql_query(join_sql, conn)
display(df_join)
conn.close()

  FirstName LastName LetterGrade
0     Alice    Smith           A
1       Bob  Johnson           B
2   Charlie    Brown           C

## Prompt: Join the Students table with the Grades table using a LEFT JOIN to see all students regardless of whether they have a grade record.

In [ ]:
# -- Topic 16: LEFT JOIN --
left_join_sql = """
SELECT Students.FirstName, Students.LastName, Grades.LetterGrade
FROM Students
LEFT JOIN Grades ON Students.StudentID = Grades.StudentID;
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Age INT,
    Major VARCHAR(100),
    GPA DECIMAL(3, 2)
);
""")
cursor.execute("""
CREATE TABLE Grades (
    GradeID INT PRIMARY KEY,
    StudentID INT,
    LetterGrade VARCHAR(2)
);
""")
cursor.execute("""
INSERT INTO Students (StudentID, FirstName, LastName, Age, Major, GPA) VALUES
(1, 'Alice', 'Smith', 20, 'Computer Science', 3.8),
(2, 'Bob', 'Johnson', 21, 'Mathematics', 3.4),
(3, 'Charlie', 'Brown', 19, 'Physics', 2.9),
(4, 'Diana', 'Davis', 22, 'Computer Science', 3.95),
(5, 'Evan', 'Miller', 20, 'Chemistry', 3.1);
""")
cursor.execute("""
INSERT INTO Grades (GradeID, StudentID, LetterGrade) VALUES
(101, 1, 'A'),
(102, 2, 'B'),
(103, 3, 'C');
""")

df_left = pd.read_sql_query(left_join_sql, conn)
display(df_left)
conn.close()

  FirstName LastName LetterGrade
0     Alice    Smith           A
1       Bob  Johnson           B
2   Charlie    Brown           C
3     Diana    Davis        None
4      Evan   Miller        None

## Prompt: Perform a RIGHT JOIN (simulated in SQLite using LEFT JOIN with swapped tables) to list all grades and their matching student records.

In [ ]:
# -- Topic 17: RIGHT JOIN --
# SQLite does not natively support RIGHT JOIN, so we simulate it by swapping the table order in a LEFT JOIN.
right_join_sql = """
SELECT Students.FirstName, Students.LastName, Grades.LetterGrade
FROM Grades
LEFT JOIN Students ON Grades.StudentID = Students.StudentID;
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Age INT,
    Major VARCHAR(100),
    GPA DECIMAL(3, 2)
);
""")
cursor.execute("""
CREATE TABLE Grades (
    GradeID INT PRIMARY KEY,
    StudentID INT,
    LetterGrade VARCHAR(2)
);
""")
cursor.execute("""
INSERT INTO Students (StudentID, FirstName, LastName, Age, Major, GPA) VALUES
(1, 'Alice', 'Smith', 20, 'Computer Science', 3.8),
(2, 'Bob', 'Johnson', 21, 'Mathematics', 3.4);
""")
cursor.execute("""
INSERT INTO Grades (GradeID, StudentID, LetterGrade) VALUES
(101, 1, 'A'),
(102, 2, 'B'),
(103, 99, 'F');
""")

df_right = pd.read_sql_query(right_join_sql, conn)
display(df_right)
conn.close()

  FirstName LastName LetterGrade
0     Alice    Smith           A
1       Bob  Johnson           B
2      None     None           F

## Prompt: Group the students by their Major and count the number of students in each major using SQL GROUP BY.

In [ ]:
# -- Topic 18: GROUP BY --
group_by_sql = """
SELECT Major, COUNT(StudentID) AS NumberOfStudents
FROM Students
GROUP BY Major;
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Age INT,
    Major VARCHAR(100),
    GPA DECIMAL(3, 2)
);
""")
cursor.execute("""
INSERT INTO Students (StudentID, FirstName, LastName, Age, Major, GPA) VALUES
(1, 'Alice', 'Smith', 20, 'Computer Science', 3.8),
(2, 'Bob', 'Johnson', 21, 'Mathematics', 3.4),
(3, 'Charlie', 'Brown', 19, 'Physics', 2.9),
(4, 'Diana', 'Davis', 22, 'Computer Science', 3.95),
(5, 'Evan', 'Miller', 20, 'Chemistry', 3.1);
""")

df_group = pd.read_sql_query(group_by_sql, conn)
display(df_group)
conn.close()

              Major  NumberOfStudents
0         Chemistry                 1
1  Computer Science                 2
2       Mathematics                 1
3           Physics                 1

## Prompt: Group students by their Major and list only those majors that have an average GPA greater than 3.2 using the HAVING clause.

In [ ]:
# -- Topic 19: HAVING Clause --
having_sql = """
SELECT Major, AVG(GPA) AS AverageGPA
FROM Students
GROUP BY Major
HAVING AVG(GPA) > 3.2;
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Age INT,
    Major VARCHAR(100),
    GPA DECIMAL(3, 2)
);
""")
cursor.execute("""
INSERT INTO Students (StudentID, FirstName, LastName, Age, Major, GPA) VALUES
(1, 'Alice', 'Smith', 20, 'Computer Science', 3.8),
(2, 'Bob', 'Johnson', 21, 'Mathematics', 3.4),
(3, 'Charlie', 'Brown', 19, 'Physics', 2.9),
(4, 'Diana', 'Davis', 22, 'Computer Science', 3.95),
(5, 'Evan', 'Miller', 20, 'Chemistry', 3.1);
""")

df_having = pd.read_sql_query(having_sql, conn)
display(df_having)
conn.close()

              Major  AverageGPA
0  Computer Science       3.875
1       Mathematics       3.400

## Prompt: Find all students who have a matching record in the Grades table using the SQL EXISTS operator.

In [ ]:
# -- Topic 20: EXISTS Operator --
exists_sql = """
SELECT FirstName, LastName
FROM Students
WHERE EXISTS (
    SELECT 1 FROM Grades
    WHERE Grades.StudentID = Students.StudentID
);
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Age INT,
    Major VARCHAR(100),
    GPA DECIMAL(3, 2)
);
""")
cursor.execute("""
CREATE TABLE Grades (
    GradeID INT PRIMARY KEY,
    StudentID INT,
    LetterGrade VARCHAR(2)
);
""")
cursor.execute("""
INSERT INTO Students (StudentID, FirstName, LastName, Age, Major, GPA) VALUES
(1, 'Alice', 'Smith', 20, 'Computer Science', 3.8),
(2, 'Bob', 'Johnson', 21, 'Mathematics', 3.4),
(3, 'Charlie', 'Brown', 19, 'Physics', 2.9);
""")
cursor.execute("""
INSERT INTO Grades (GradeID, StudentID, LetterGrade) VALUES
(101, 1, 'A'),
(102, 2, 'B');
""")

df_exists = pd.read_sql_query(exists_sql, conn)
display(df_exists)
conn.close()

  FirstName LastName
0     Alice    Smith
1       Bob  Johnson

## Prompt: Find students whose GPA is larger than the GPA of ALL students in the 'Physics' major using SQL comparisons.

In [ ]:
# -- Topic 21: ANY / ALL Operators --
# SQLite does not natively support the ALL keyword, so we simulate it using a subquery with MAX() or logical comparison.
all_sql = """
SELECT FirstName, LastName, GPA
FROM Students
WHERE GPA > (SELECT MAX(GPA) FROM Students WHERE Major = 'Physics');
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Age INT,
    Major VARCHAR(100),
    GPA DECIMAL(3, 2)
);
""")
cursor.execute("""
INSERT INTO Students (StudentID, FirstName, LastName, Age, Major, GPA) VALUES
(1, 'Alice', 'Smith', 20, 'Computer Science', 3.8),
(2, 'Bob', 'Johnson', 21, 'Mathematics', 3.4),
(3, 'Charlie', 'Brown', 19, 'Physics', 2.9);
""")

df_all_op = pd.read_sql_query(all_sql, conn)
display(df_all_op)
conn.close()

  FirstName LastName  GPA
0     Alice    Smith  3.8
1       Bob  Johnson  3.4

## Prompt: Create a new backup table containing only students majoring in 'Computer Science' using the SQL SELECT INTO equivalent (CREATE TABLE AS).

In [ ]:
# -- Topic 22: SELECT INTO --
# Since SQLite does not support SELECT INTO, we use the standard equivalent: CREATE TABLE AS SELECT.
select_into_sql = """
CREATE TABLE CS_Students_Backup AS
SELECT * FROM Students
WHERE Major = 'Computer Science';
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Age INT,
    Major VARCHAR(100),
    GPA DECIMAL(3, 2)
);
""")
cursor.execute("""
INSERT INTO Students (StudentID, FirstName, LastName, Age, Major, GPA) VALUES
(1, 'Alice', 'Smith', 20, 'Computer Science', 3.8),
(2, 'Bob', 'Johnson', 21, 'Mathematics', 3.4),
(3, 'Charlie', 'Brown', 19, 'Physics', 2.9),
(4, 'Diana', 'Davis', 22, 'Computer Science', 3.95);
""")

cursor.execute(select_into_sql)
df_backup = pd.read_sql_query("SELECT * FROM CS_Students_Backup;", conn)
display(df_backup)
conn.close()

   StudentID FirstName LastName  Age             Major   GPA
0          1     Alice    Smith   20  Computer Science  3.80
1          4     Diana    Davis   22  Computer Science  3.95

## Prompt: Insert records of high-achieving students (GPA > 3.5) from the Students table into an existing HonorsList table using INSERT INTO SELECT.

In [ ]:
# -- Topic 23: INSERT INTO SELECT --
insert_into_select_sql = """
INSERT INTO HonorsList (StudentID, Name, CurrentGPA)
SELECT StudentID, FirstName || ' ' || LastName, GPA
FROM Students
WHERE GPA > 3.5;
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Age INT,
    Major VARCHAR(100),
    GPA DECIMAL(3, 2)
);
""")
cursor.execute("""
CREATE TABLE HonorsList (
    StudentID INT PRIMARY KEY,
    Name VARCHAR(100),
    CurrentGPA DECIMAL(3, 2)
);
""")
cursor.execute("""
INSERT INTO Students (StudentID, FirstName, LastName, Age, Major, GPA) VALUES
(1, 'Alice', 'Smith', 20, 'Computer Science', 3.8),
(2, 'Bob', 'Johnson', 21, 'Mathematics', 3.4),
(3, 'Charlie', 'Brown', 19, 'Physics', 2.9),
(4, 'Diana', 'Davis', 22, 'Computer Science', 3.95);
""")

cursor.execute(insert_into_select_sql)
df_honors = pd.read_sql_query("SELECT * FROM HonorsList;", conn)
display(df_honors)
conn.close()

   StudentID         Name  CurrentGPA
0          1  Alice Smith        3.80
1          4  Diana Davis        3.95

## Prompt: Demonstrate standard SQL Constraints including NOT NULL, UNIQUE, DEFAULT, CHECK, and FOREIGN KEY using SQLite.

In [ ]:
# -- Topic 24: SQL Constraints --
# This script demonstrates various SQL constraints including NOT NULL, UNIQUE, DEFAULT, CHECK, and FOREIGN KEY.

constraints_setup_sql = """
-- 1. Create a parent table with PRIMARY KEY and UNIQUE constraints
CREATE TABLE IF NOT EXISTS Departments (
    DeptID INTEGER PRIMARY KEY,
    DeptName TEXT NOT NULL UNIQUE
);

-- 2. Create a child table with NOT NULL, DEFAULT, CHECK, and FOREIGN KEY constraints
CREATE TABLE IF NOT EXISTS Employees (
    EmpID INTEGER PRIMARY KEY,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    Email TEXT UNIQUE,
    Status TEXT DEFAULT 'Active',
    Salary REAL CHECK(Salary > 0),
    DeptID INTEGER,
    FOREIGN KEY (DeptID) REFERENCES Departments(DeptID)
);
"""

import sqlite3
import pandas as pd

# Establish an in-memory SQLite database connection
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# SQLite needs foreign key constraint enforcement explicitly enabled
cursor.execute("PRAGMA foreign_keys = ON;")

# Execute setup statements
cursor.executescript(constraints_setup_sql)

# Seed parent table
cursor.execute("INSERT INTO Departments (DeptID, DeptName) VALUES (10, 'Engineering'), (20, 'Human Resources');")

# Insert valid records
cursor.execute("""
INSERT INTO Employees (EmpID, FirstName, LastName, Email, Status, Salary, DeptID)
VALUES (1, 'Alice', 'Smith', 'alice@company.com', 'Active', 95000.0, 10);
""")

# Insert record relying on DEFAULT Status constraint
cursor.execute("""
INSERT INTO Employees (EmpID, FirstName, LastName, Email, Salary, DeptID)
VALUES (2, 'Bob', 'Jones', 'bob@company.com', 80000.0, 20);
""")

print("--- Departments Table ---")
df_depts = pd.read_sql_query("SELECT * FROM Departments;", conn)
display(df_depts)

print("\n--- Employees Table (Valid Records) ---")
df_emps = pd.read_sql_query("SELECT * FROM Employees;", conn)
display(df_emps)

# Demonstrate constraint violations gracefully using try-except blocks
print("\n--- Constraint Failure Demonstrations ---")

try:
    # Violating NOT NULL constraint
    cursor.execute("INSERT INTO Employees (EmpID, FirstName, LastName, Salary) VALUES (3, NULL, 'White', 50000.0);")
except sqlite3.IntegrityError as e:
    print(f"NOT NULL Violation Triggered: {e}")

try:
    # Violating UNIQUE constraint on Email
    cursor.execute("INSERT INTO Employees (EmpID, FirstName, LastName, Email, Salary) VALUES (4, 'John', 'Doe', 'alice@company.com', 60000.0);")
except sqlite3.IntegrityError as e:
    print(f"UNIQUE Violation Triggered: {e}")

try:
    # Violating CHECK constraint on Salary
    cursor.execute("INSERT INTO Employees (EmpID, FirstName, LastName, Salary) VALUES (5, 'Charlie', 'Brown', -100.0);")
except sqlite3.IntegrityError as e:
    print(f"CHECK Violation Triggered: {e}")

try:
    # Violating FOREIGN KEY constraint by passing non-existent DeptID
    cursor.execute("INSERT INTO Employees (EmpID, FirstName, LastName, Salary, DeptID) VALUES (6, 'Diana', 'Prince', 75000.0, 99);")
except sqlite3.IntegrityError as e:
    print(f"FOREIGN KEY Violation Triggered: {e}")

conn.close()

--- Departments Table ---

   DeptID         DeptName
0      10      Engineering
1      20  Human Resources

--- Employees Table (Valid Records) ---

   EmpID FirstName LastName              Email  Status   Salary  DeptID
0      1     Alice    Smith  alice@company.com  Active  95000.0      10
1      2       Bob    Jones    bob@company.com  Active  80000.0      20

--- Constraint Failure Demonstrations ---
NOT NULL Violation Triggered: NOT NULL constraint failed: Employees.FirstName
UNIQUE Violation Triggered: UNIQUE constraint failed: Employees.Email
CHECK Violation Triggered: CHECK constraint failed: Salary > 0
FOREIGN KEY Violation Triggered: FOREIGN KEY constraint failed

## Prompt: Categorize students based on their GPA using the SQL CASE statement.

In [ ]:
# -- Topic 25: SQL CASE Statement --
case_sql = """
SELECT FirstName, LastName, GPA,
       CASE
           WHEN GPA >= 3.8 THEN 'Excellent'
           WHEN GPA >= 3.4 THEN 'Good'
           ELSE 'Average'
       END AS PerformanceCategory
FROM Students;
"""

import sqlite3
import pandas as pd

# Establish an in-memory SQLite database connection
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Re-create Students table and populate it
cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Age INT,
    Major VARCHAR(100),
    GPA DECIMAL(3, 2)
);
""")

cursor.execute("""
INSERT INTO Students (StudentID, FirstName, LastName, Age, Major, GPA) VALUES
(1, 'Alice', 'Smith', 20, 'Computer Science', 3.8),
(2, 'Bob', 'Johnson', 21, 'Mathematics', 3.4),
(3, 'Charlie', 'Brown', 19, 'Physics', 2.9),
(4, 'Diana', 'Davis', 22, 'Computer Science', 3.95),
(5, 'Evan', 'Miller', 20, 'Chemistry', 3.1);
""")

# Run the CASE query and display the results
df_case = pd.read_sql_query(case_sql, conn)
display(df_case)

conn.close()

  FirstName LastName   GPA PerformanceCategory
0     Alice    Smith  3.80           Excellent
1       Bob  Johnson  3.40                Good
2   Charlie    Brown  2.90             Average
3     Diana    Davis  3.95           Excellent
4      Evan   Miller  3.10             Average

## Prompt: Demonstrate how to register and use a User-Defined Function (UDF) in SQLite as an alternative to standard SQL functions/procedures.

In [ ]:
# -- Topic 26: SQL User-Defined Functions --
# Standard SQLite does not support stored procedures (CREATE PROCEDURE).
# Instead, we register custom scalar functions using python's sqlite3 API and invoke them using standard SQL.

import sqlite3
import pandas as pd

# 1. Define a standard Python function to calculate grade status based on GPA
def get_gpa_status(gpa):
    if gpa >= 3.5:
        return "Honor Roll"
    elif gpa >= 3.0:
        return "Satisfactory"
    else:
        return "Needs Improvement"

# Establish connection
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# 2. Register our Python function as a SQL function named 'GPA_STATUS' taking 1 argument
conn.create_function("GPA_STATUS", 1, get_gpa_status)

# Create and populate Students table
cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    GPA DECIMAL(3, 2)
);
""")

cursor.execute("""
INSERT INTO Students (StudentID, FirstName, LastName, GPA) VALUES
(1, 'Alice', 'Smith', 3.8),
(2, 'Bob', 'Johnson', 3.4),
(3, 'Charlie', 'Brown', 2.9);
""")

# 3. Execute a SQL query utilizing our registered User-Defined Function
udf_sql = """
SELECT FirstName, LastName, GPA, GPA_STATUS(GPA) AS AcademicStatus
FROM Students;
"""

df_udf = pd.read_sql_query(udf_sql, conn)
display(df_udf)

conn.close()

  FirstName LastName  GPA     AcademicStatus
0     Alice    Smith  3.8         Honor Roll
1       Bob  Johnson  3.4       Satisfactory
2   Charlie    Brown  2.9  Needs Improvement

## Prompt: Perform a database backup programmatically in SQLite using python's connection backup API.

In [ ]:
# -- Topic 27: Database Backup --
# Since SQLite does not have a standard 'BACKUP DATABASE' SQL command like other heavy engines,
# we use the standard Python SQLite3 backup API to clone our database cleanly into a physical file.

import sqlite3
import os

# 1. Establish an in-memory database and populate it with sample data
source_conn = sqlite3.connect(':memory:')
source_cursor = source_conn.cursor()

source_cursor.execute("""
CREATE TABLE IF NOT EXISTS SourceData (
    ID INTEGER PRIMARY KEY,
    Name TEXT NOT NULL
);
""")
source_cursor.execute("INSERT INTO SourceData (ID, Name) VALUES (1, 'Main Database Entry');")
source_conn.commit()

print("Source database initialized with sample records.")

# 2. Define our target backup file path
backup_file_path = "student_db_backup.db"

# Remove existing backup if it already exists
if os.path.exists(backup_file_path):
    os.remove(backup_file_path)

# 3. Establish a connection to the target backup database file
backup_conn = sqlite3.connect(backup_file_path)

# 4. Use python's sqlite3 backup API to copy the database dynamically and safely
with backup_conn:
    source_conn.backup(backup_conn)

print(f"Database backup completed successfully! Destination file: {backup_file_path}")

# 5. Verify the backup contains the correct data
verify_cursor = backup_conn.cursor()
verify_cursor.execute("SELECT * FROM SourceData;")
rows = verify_cursor.fetchall()
print(f"Verified backup content: {rows}")

# Clean up connections
backup_conn.close()
source_conn.close()

Source database initialized with sample records.
Database backup completed successfully! Destination file: student_db_backup.db
Verified backup content: [(1, 'Main Database Entry')]

## Prompt: Perform an INNER JOIN between Students and Departments tables to fetch each student's name and department name.

In [ ]:
# -- Topic 28: INNER JOIN (Students & Departments) --
students_dept_join_sql = """
SELECT Students.FirstName, Students.LastName, Departments.DeptName
FROM Students
INNER JOIN Departments ON Students.DeptID = Departments.DeptID;
"""

import sqlite3
import pandas as pd

# Establish an in-memory SQLite database connection
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Create Departments Table
cursor.execute("""
CREATE TABLE Departments (
    DeptID INT PRIMARY KEY,
    DeptName VARCHAR(100)
);
""")

# Create Students Table with DeptID column
cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    DeptID INT
);
""")

# Insert Department Records
cursor.execute("""
INSERT INTO Departments (DeptID, DeptName) VALUES
(10, 'Computer Science'),
(20, 'Mathematics'),
(30, 'Physics');
""")

# Insert Student Records
cursor.execute("""
INSERT INTO Students (StudentID, FirstName, LastName, DeptID) VALUES
(1, 'Alice', 'Smith', 10),
(2, 'Bob', 'Johnson', 20),
(3, 'Charlie', 'Brown', 10),
(4, 'Diana', 'Davis', 30);
""")

# Execute INNER JOIN and display results
df_dept_join = pd.read_sql_query(students_dept_join_sql, conn)
display(df_dept_join)

conn.close()

  FirstName LastName          DeptName
0     Alice    Smith  Computer Science
1       Bob  Johnson       Mathematics
2   Charlie    Brown  Computer Science
3     Diana    Davis           Physics

## Prompt: Perform a RIGHT JOIN (simulated in SQLite) between Students and Departments tables to display all departments, including those with no enrolled students.

In [ ]:
# -- Topic 29: RIGHT JOIN --
# Since SQLite does not natively support RIGHT JOIN, we achieve this by swapping the
# order of the tables in a LEFT JOIN so that all rows from the right-hand table
# (Departments) are included, even if no matching students exist.

students_dept_right_join_sql = """
SELECT Students.FirstName, Students.LastName, Departments.DeptName
FROM Departments
LEFT JOIN Students ON Departments.DeptID = Students.DeptID;
"""

import sqlite3
import pandas as pd

# Establish an in-memory SQLite database connection
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Create Tables
cursor.execute("""
CREATE TABLE Departments (
    DeptID INT PRIMARY KEY,
    DeptName VARCHAR(100)
);
""")

cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    DeptID INT
);
""")

# Insert Department Records (including 'Chemistry' which will have no students)
cursor.execute("""
INSERT INTO Departments (DeptID, DeptName) VALUES
(10, 'Computer Science'),
(20, 'Mathematics'),
(30, 'Physics'),
(40, 'Chemistry');
""")

# Insert Student Records
cursor.execute("""
INSERT INTO Students (StudentID, FirstName, LastName, DeptID) VALUES
(1, 'Alice', 'Smith', 10),
(2, 'Bob', 'Johnson', 20),
(3, 'Charlie', 'Brown', 10);
""")

# Execute simulated RIGHT JOIN and display results
df_dept_right_join = pd.read_sql_query(students_dept_right_join_sql, conn)
display(df_dept_right_join)

conn.close()

  FirstName LastName          DeptName
0     Alice    Smith  Computer Science
1   Charlie    Brown  Computer Science
2       Bob  Johnson       Mathematics
3      None     None           Physics
4      None     None         Chemistry

## Prompt: Compare the outputs of INNER JOIN, LEFT JOIN, and RIGHT JOIN side-by-side using a unified summary table.

In [ ]:
# -- Topic 30: Joins Comparison Summary --
import sqlite3
import pandas as pd

# Establish an in-memory SQLite database connection
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Re-create and populate the standard tables used in previous joins
cursor.execute("""
CREATE TABLE Departments (
    DeptID INT PRIMARY KEY,
    DeptName VARCHAR(100)
);
""")

cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    DeptID INT
);
""")

cursor.execute("""
INSERT INTO Departments (DeptID, DeptName) VALUES
(10, 'Computer Science'),
(20, 'Mathematics'),
(30, 'Physics'),
(40, 'Chemistry');
""")

cursor.execute("""
INSERT INTO Students (StudentID, FirstName, LastName, DeptID) VALUES
(1, 'Alice', 'Smith', 10),
(2, 'Bob', 'Johnson', 20),
(3, 'Charlie', 'Brown', 10),
(4, 'Diana', 'Davis', 30);
""")

# Define the three join queries
inner_join_query = """
SELECT Students.FirstName, Students.LastName, Departments.DeptName
FROM Students
INNER JOIN Departments ON Students.DeptID = Departments.DeptID;
"""

left_join_query = """
SELECT Students.FirstName, Students.LastName, Departments.DeptName
FROM Students
LEFT JOIN Departments ON Students.DeptID = Departments.DeptID;
"""

# Swapping the order of tables in LEFT JOIN to simulate RIGHT JOIN
right_join_query = """
SELECT Students.FirstName, Students.LastName, Departments.DeptName
FROM Departments
LEFT JOIN Students ON Departments.DeptID = Students.DeptID;
"""

# Fetch dataframes
df_inner = pd.read_sql_query(inner_join_query, conn)
df_left = pd.read_sql_query(left_join_query, conn)
df_right = pd.read_sql_query(right_join_query, conn)

# Display each join type outcome
print("=== 1. INNER JOIN RESULT ===\n(Only matching rows from BOTH tables)")
display(df_inner)

print("\n=== 2. LEFT JOIN RESULT ===\n(All rows from Students, with matched Departments)")
display(df_left)

print("\n=== 3. RIGHT JOIN RESULT ===\n(All rows from Departments, with matched Students)")
display(df_right)

conn.close()

=== 1. INNER JOIN RESULT ===
(Only matching rows from BOTH tables)

  FirstName LastName          DeptName
0     Alice    Smith  Computer Science
1       Bob  Johnson       Mathematics
2   Charlie    Brown  Computer Science
3     Diana    Davis           Physics

=== 2. LEFT JOIN RESULT ===
(All rows from Students, with matched Departments)

  FirstName LastName          DeptName
0     Alice    Smith  Computer Science
1       Bob  Johnson       Mathematics
2   Charlie    Brown  Computer Science
3     Diana    Davis           Physics

=== 3. RIGHT JOIN RESULT ===
(All rows from Departments, with matched Students)

  FirstName LastName          DeptName
0     Alice    Smith  Computer Science
1   Charlie    Brown  Computer Science
2       Bob  Johnson       Mathematics
3     Diana    Davis           Physics
4      None     None         Chemistry

## Prompt: Combine lists of students and employees into a single unified directory using the UNION operator, and filter the combined results to find people named 'Alice' using an outer query.

In [ ]:
# -- Topic 31: Filtering a UNION Query --
# To filter the combined results of a UNION, we wrap the entire UNION operation
# inside a subquery (or a Common Table Expression / CTE) and apply a WHERE clause on the outer query.

filtered_union_sql = """
SELECT *
FROM (
    SELECT FirstName, LastName, 'Student' AS Role FROM Students
    UNION
    SELECT FirstName, LastName, 'Employee' AS Role FROM Employees
) AS CombinedDirectory
WHERE FirstName = 'Alice';
"""

import sqlite3
import pandas as pd

# Establish an in-memory SQLite database connection
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Create Tables
cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50)
);
""")

cursor.execute("""
CREATE TABLE Employees (
    EmpID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50)
);
""")

# Populate Tables
cursor.execute("""
INSERT INTO Students (StudentID, FirstName, LastName) VALUES
(1, 'Alice', 'Smith'),
(2, 'Bob', 'Johnson'),
(3, 'Charlie', 'Brown');
""")

cursor.execute("""
INSERT INTO Employees (EmpID, FirstName, LastName) VALUES
(101, 'Alice', 'Cooper'),
(102, 'David', 'Miller'),
(103, 'Evan', 'Wright');
""")

# Run the filtered UNION query
df_filtered_union = pd.read_sql_query(filtered_union_sql, conn)
display(df_filtered_union)

conn.close()

  FirstName LastName      Role
0     Alice   Cooper  Employee
1     Alice    Smith   Student

###Prompt: Summarize the above all topics cover in this file.

## Comprehensive SQL Topics Summary

This notebook provides a practical, hands-on guide to essential and advanced SQL concepts using SQLite in Python. Below is a summary of the 31 core topics covered across the notebook:

### 1. Basic Database Operations (CRUD)
*   **CREATE TABLE (Topic 1):** Designing table schemas with defined columns and data types.
*   **INSERT INTO (Topic 2):** Adding new records into tables.
*   **SELECT (Topic 3):** Querying and retrieving records from tables.
*   **WHERE (Topic 4):** Filtering rows based on specific conditions.
*   **AND/OR (Topic 5):** Combining multiple query filtering criteria.
*   **UPDATE (Topic 6):** Modifying existing database records.
*   **DELETE (Topic 7):** Removing specific records from tables.

### 2. Filtering, Sorting, and Searching
*   **ORDER BY (Topic 8):** Sorting query results in ascending (`ASC`) or descending (`DESC`) order.
*   **LIKE Operator (Topic 11):** Performing pattern matching on text columns (e.g., finding names starting with 'A' using `A%`).
*   **IN Operator (Topic 12):** Filtering rows by checking if a value matches any item in a specified list.
*   **BETWEEN Operator (Topic 13):** Querying values within a specific inclusive range.
*   **Aliases (Topic 14):** Renaming columns or tables temporarily using `AS` for better readability.

### 3. Aggregate Functions & Grouping
*   **MIN() and MAX() (Topic 9):** Finding the minimum and maximum values in a column.
*   **COUNT(), AVG(), SUM() (Topic 10):** Standard mathematical aggregations to count rows, calculate averages, and sum numeric attributes.
*   **GROUP BY (Topic 18):** Aggregating and summarizing data by categorizing rows based on one or more columns.
*   **HAVING Clause (Topic 19):** Filtering groups created by a `GROUP BY` clause using aggregate conditions (similar to a `WHERE` clause for groups).

### 4. Advanced Joins and Set Operations
*   **INNER JOIN (Topics 15, 28):** Fetching rows with matching keys in both participating tables.
*   **LEFT JOIN (Topic 16):** Retrieving all records from the left table and matched records from the right table.
*   **RIGHT JOIN Simulation (Topics 17, 29):** Simulating a RIGHT JOIN in SQLite (which doesn't support it natively) by swapping the table order in a `LEFT JOIN`.
*   **Joins Comparison (Topic 30):** Comparing the distinct behavioral outputs of `INNER`, `LEFT`, and simulated `RIGHT` joins side-by-side.
*   **Filtering a UNION (Topic 31):** Combining outputs of multiple `SELECT` queries using `UNION`, and wrapping them in an outer query to perform custom filtering.

### 5. Conditional Logic and Subqueries
*   **EXISTS Operator (Topic 20):** Checking for the presence of matching records in a related subquery.
*   **ANY / ALL Operators Simulation (Topic 21):** Simulating comparison operators against subqueries using aggregation functions like `MAX` in SQLite.
*   **SELECT INTO / CREATE TABLE AS (Topic 22):** Duplicating table structure and seeding it with filtered data dynamically.
*   **INSERT INTO SELECT (Topic 23):** Inserting records into an existing table by pulling data directly from another table's query result.
*   **SQL CASE Statement (Topic 25):** Applying conditional `IF-THEN-ELSE` logic inside standard SQL queries to categorize values on the fly.

### 6. Integrity, Custom Functions, and Utilities
*   **SQL Constraints (Topic 24):** Guaranteeing database integrity using `NOT NULL`, `UNIQUE`, `DEFAULT`, `CHECK` expressions, and establishing relationships via `FOREIGN KEY` references.
*   **User-Defined Functions (Topic 26):** Registering custom Python functions inside SQLite with `conn.create_function()` to execute custom logic as native SQL functions.
*   **Database Backup (Topic 27):** Executing logical hot-backups of active databases dynamically into physical disk files using python's sqlite3 connection backup API.